# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.12 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.12")
   message(FATAL_ERROR "CMake >= 2.8.12 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.12...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS atom_types value atombase columnvec atomcore execution atomflow foreign grounded join parallel pattern clearbox rule truthvalue atomspace query-engine exec logger randgen type-utils smob)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target atom_types
add_library(atom_types SHARED IMPORTED)

set_target_properties(atom_types PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target value
add_library(value SHARED IMPORTED)

set_target_properties(value PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atom_types;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target atombase
add_library(atombase SHARED IMPORTED)

set_target_properties(atombase PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atom_types;value;truthvalue;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target columnvec
add_library(columnvec SHARED IMPORTED)

set_target_properties(columnvec PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atomcore;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target atomcore
add_library(atomcore SHARED IMPORTED)

set_target_properties(atomcore PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target execution
add_library(execution SHARED IMPORTED)

set_target_properties(execution PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;parallel;clearbox;atomflow;atomcore;atombase"
)

# Create imported target atomflow
add_library(atomflow SHARED IMPORTED)

set_target_properties(atomflow PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atomcore;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target foreign
add_library(foreign SHARED IMPORTED)

set_target_properties(foreign PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target grounded
add_library(grounded SHARED IMPORTED)

set_target_properties(grounded PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atombase"
)

# Create imported target join
add_library(join SHARED IMPORTED)

set_target_properties(join PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atomcore;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target parallel
add_library(parallel SHARED IMPORTED)

set_target_properties(parallel PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atomcore;atombase"
)

# Create imported target pattern
add_library(pattern SHARED IMPORTED)

set_target_properties(pattern PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;query-engine;rule;atomcore;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target clearbox
add_library(clearbox SHARED IMPORTED)

set_target_properties(clearbox PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atom_types;atomcore;atombase;value;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target rule
add_library(rule SHARED IMPORTED)

set_target_properties(rule PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atomcore;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target truthvalue
add_library(truthvalue SHARED IMPORTED)

set_target_properties(truthvalue PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;value;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target atomspace
add_library(atomspace SHARED IMPORTED)

set_target_properties(atomspace PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;-Wl,--no-as-needed;clearbox;join;pattern;grounded;execution;atomflow;atomcore;atombase;truthvalue;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target query-engine
add_library(query-engine SHARED IMPORTED)

set_target_properties(query-engine PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;execution"
)

# Create imported target exec
add_library(exec SHARED IMPORTED)

set_target_properties(exec PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;execution;smob"
)

# Create imported target logger
add_library(logger SHARED IMPORTED)

set_target_properties(logger PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;smob;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target randgen
add_library(randgen SHARED IMPORTED)

set_target_properties(randgen PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;smob;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target type-utils
add_library(type-utils SHARED IMPORTED)

set_target_properties(type-utils PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atomcore;smob"
)

# Create imported target smob
add_library(smob SHARED IMPORTED)

set_target_properties(smob PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;-Wl,--no-as-needed;clearbox;join;pattern;execution;columnvec;atomflow;atomcore;foreign;atombase;truthvalue;atomspace;/usr/lib/x86_64-linux-gnu/libguile-3.0.so;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/AtomSpaceTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
