# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.12 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.12")
   message(FATAL_ERROR "CMake >= 2.8.12 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.12...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS storage-types persist csv csv-table fast_load_scm persist-file persist-flow json datalog persist-proxy sexcom sexpr tlb guile-uuid)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target storage-types
add_library(storage-types SHARED IMPORTED)

set_target_properties(storage-types PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atom_types"
)

# Create imported target persist
add_library(persist SHARED IMPORTED)

set_target_properties(persist PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;storage-types;atomspace;smob"
)

# Create imported target csv
add_library(csv SHARED IMPORTED)

set_target_properties(csv PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atomspace;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target csv-table
add_library(csv-table SHARED IMPORTED)

set_target_properties(csv-table PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;csv;atomspace;smob"
)

# Create imported target fast_load_scm
add_library(fast_load_scm SHARED IMPORTED)

set_target_properties(fast_load_scm PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;sexcom;sexpr"
)

# Create imported target persist-file
add_library(persist-file SHARED IMPORTED)

set_target_properties(persist-file PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;persist;storage-types;fast_load_scm;sexcom;sexpr;atomspace;smob"
)

# Create imported target persist-flow
add_library(persist-flow SHARED IMPORTED)

set_target_properties(persist-flow PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;persist;atom_types;value;atombase;atomcore;atomflow;columnvec;truthvalue;clearbox;join;pattern;query-engine;execution;grounded;smob;atomspace;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target json
add_library(json SHARED IMPORTED)

set_target_properties(json PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atomspace;execution;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target datalog
add_library(datalog SHARED IMPORTED)

set_target_properties(datalog PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atomspace;execution;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target persist-proxy
add_library(persist-proxy SHARED IMPORTED)

set_target_properties(persist-proxy PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;persist;atomcore;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target sexcom
add_library(sexcom SHARED IMPORTED)

set_target_properties(sexcom PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;storage-types;persist-proxy;persist;atomspace;execution;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target sexpr
add_library(sexpr SHARED IMPORTED)

set_target_properties(sexpr PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atomspace;atombase;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target tlb
add_library(tlb SHARED IMPORTED)

set_target_properties(tlb PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;atombase;atomspace;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Create imported target guile-uuid
add_library(guile-uuid STATIC IMPORTED)

set_target_properties(guile-uuid PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;SHARED;tlb;atom_types;value;atombase;atomcore;atomflow;columnvec;truthvalue;clearbox;join;pattern;query-engine;execution;grounded;smob;atomspace;/home/runner/work/opencog-basic/opencog-basic/install/lib/opencog/libcogutil.so"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/AtomSpaceStorageTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
