/* File automatically generated by the macro OPENCOG_CXX_ATOMTYPES. Do not edit */
#include <opencog/atoms/atom_types/types.h>
namespace opencog
{
extern opencog::Type STORAGE_NODE;
extern opencog::Type POSTGRES_STORAGE_NODE;
extern opencog::Type FILE_STORAGE_NODE;
extern opencog::Type MONO_STORAGE_NODE;
extern opencog::Type ROCKS_STORAGE_NODE;
extern opencog::Type COG_SIMPLE_STORAGE_NODE;
extern opencog::Type COG_STORAGE_NODE;
extern opencog::Type FOREIGN_STORAGE_NODE;
extern opencog::Type BRIDGE_STORAGE_NODE;
extern opencog::Type PROXY_NODE;
extern opencog::Type NULL_PROXY_NODE;
extern opencog::Type READ_THRU_PROXY_NODE;
extern opencog::Type SEQUENTIAL_READ_PROXY_NODE;
extern opencog::Type WRITE_THRU_PROXY_NODE;
extern opencog::Type READ_WRITE_PROXY_NODE;
extern opencog::Type WRITE_BUFFER_PROXY_NODE;
extern opencog::Type CACHING_PROXY_NODE;
extern opencog::Type DYNAMIC_DATA_PROXY_NODE;
extern opencog::Type PROXY_PARAMETERS_LINK;
extern opencog::Type FETCH_VALUE_OF_LINK;
extern opencog::Type STORE_VALUE_OF_LINK;
} // namespace opencog
